### ISSUE TITLE
omnitrace-avail --advanced option for settings

### ISSUE THREAD

**Issue by jrmadsen** [AMDResearch/omnitrace#106]
- Several configuration options do not need to be displayed in most scenarios
  - These options make the more important options less visible / noticeable
  - Examples include:
    - `OMNITRACE_PERFETTO_SHMEM_SIZE_HINT_KB`
    - `OMNITRACE_CRITICAL_TRACE_BUFFER_COUNT` (most of the critical-trace options, honestly)
    - etc. 
- Propose adding the `"advanced"` category to several options and only displaying/dumping these command-line options in omnitrace-avail if the `--advanced` flag is provided

**Comment by jrmadsen** [comment]
Here is the first pass as what are probably advanced options:

## Miscellaneous General Options

- OMNITRACE_CPU_AFFINITY
- OMNITRACE_DL_VERBOSE
- OMNITRACE_ENABLE_SIGNAL_HANDLER
- OMNITRACE_INSTRUMENTATION_INTERVAL
- OMNITRACE_KOKKOS_KERNEL_LOGGER
- OMNITRACE_PERFETTO_BUFFER_SIZE_KB
- OMNITRACE_PERFETTO_SHMEM_SIZE_HINT_KB
- OMNITRACE_ROCTRACER_HSA_API_TYPES

## Miscellaneous Timemory-Specific Options

- OMNITRACE_MAX_DEPTH
- OMNITRACE_PAPI_FAIL_ON_ERROR
- OMNITRACE_PAPI_OVERFLOW
- OMNITRACE_PAPI_THREADING

## Critical Trace Options

- OMNITRACE_CRITICAL_TRACE_BUFFER_COUNT
- OMNITRACE_CRITICAL_TRACE_COUNT
- OMNITRACE_CRITICAL_TRACE_DEBUG
- OMNITRACE_CRITICAL_TRACE_NUM_THREADS
- OMNITRACE_CRITICAL_TRACE_PER_ROW
- OMNITRACE_CRITICAL_TRACE_SERIALIZE_NAMES

## I/O Options

- OMNITRACE_DIFF_OUTPUT
- OMNITRACE_FILE_OUTPUT
- OMNITRACE_INPUT_EXTENSIONS
- OMNITRACE_INPUT_PATH
- OMNITRACE_INPUT_PREFIX

## Flat/timeline Options

- OMNITRACE_FLAT_PROFILE
- OMNITRACE_FLAT_SAMPLING
- OMNITRACE_TIMELINE_PROFILE
- OMNITRACE_TIMELINE_SAMPLING
- OMNITRACE_ROCTRACER_FLAT_PROFILE
- OMNITRACE_ROCTRACER_TIMELINE_PROFILE

## Timemory Data Formatting Options

- OMNITRACE_MAX_WIDTH
- OMNITRACE_MEMORY_PRECISION
- OMNITRACE_MEMORY_SCIENTIFIC
- OMNITRACE_MEMORY_UNITS
- OMNITRACE_MEMORY_WIDTH
- OMNITRACE_SCIENTIFIC
- OMNITRACE_TIMING_PRECISION
- OMNITRACE_TIMING_SCIENTIFIC
- OMNITRACE_TIMING_UNITS
- OMNITRACE_TIMING_WIDTH
- OMNITRACE_WIDTH
- OMNITRACE_PRECISION

**Comment by arghdos** [comment]
Did a quick pass, these are probably my "advanced" options:

| OMNITRACE_CRITICAL_TRACE_DEBUG            | Enable debugging for critical trace                                                                           |
| OMNITRACE_CRITICAL_TRACE_NUM_THREADS      | Number of threads to use when generating the critical trace                                                  (what's default?) |
| OMNITRACE_CRITICAL_TRACE_PER_ROW          | How many critical traces per row in perfetto (0 == all in one row)                                            |
| OMNITRACE_CRITICAL_TRACE_SERIALIZE_NAMES  | Include names in serialization of critical trace (mainly for debugging)                                       |
| OMNITRACE_DEBUG                           | Enable debug output                                                                                           |
| OMNITRACE_DIFF_OUTPUT                     | Generate a difference output vs. a pre-existing output (see also: INPUT_PATH and INPUT_PREFIX)                |
| OMNITRACE_DL_VERBOSE                      | Verbosity within the omnitrace-dl library                                                                     |
| OMNITRACE_ENABLE_SIGNAL_HANDLER           | Enable signals in timemory_init                                                                               |
| OMNITRACE_FLAT_SAMPLING                   | Ignore hierarchy in all statistical sampling entries                                                          |
| OMNITRACE_INSTRUMENTATION_INTERVAL        | Instrumentation only takes measurements once every N function calls (not statistical)                         |
| OMNITRACE_JSON_OUTPUT                     | Write json output files                                                                                       |
| OMNITRACE_MAX_DEPTH                       | Set the maximum depth of label hierarchy reporting                                                            |
| OMNITRACE_MAX_WIDTH                       | Set the maximum width for component label outputs                                                             |
| OMNITRACE_MEMORY_PRECISION                | Set the precision for components with 'is_memory_category' type-trait                                         |
| OMNITRACE_MEMORY_SCIENTIFIC               | Set the numerical reporting format for components with 'is_memory_category' type-trait                        |
| OMNITRACE_MEMORY_UNITS                    | Set the units for components with 'uses_memory_units' type-trait                                              |
| OMNITRACE_MEMORY_WIDTH                    | Set the output width for components with 'is_memory_category' type-trait                                      |
| OMNITRACE_NETWORK_INTERFACE               | Default network interface                                                                                     |
| OMNITRACE_NODE_COUNT                      | Total number of nodes used in application. Setting this value > 1 will result in aggregating N processes i... |
| OMNITRACE_OUTPUT_FILE                     | [DEPRECATED] See OMNITRACE_PERFETTO_FILE                                                                      |
| OMNITRACE_PAPI_FAIL_ON_ERROR              | Configure PAPI errors to trigger a runtime error                                                              |
| OMNITRACE_PAPI_MULTIPLEXING               | Enable multiplexing when using PAPI                                                                           |
| OMNITRACE_PAPI_OVERFLOW                   | Value at which PAPI hw counters trigger an overflow callback                                                  |
| OMNITRACE_PAPI_QUIET                      | Configure suppression of reporting PAPI errors/warnings                                                       |
| OMNITRACE_PAPI_THREADING                  | Enable multithreading support when using PAPI                                                                 |
| OMNITRACE_PERFETTO_CATEGORIES             | Categories to collect within perfetto                                                                         |
| OMNITRACE_PERFETTO_COMBINE_TRACES         | Combine Perfetto traces. If not explicitly set, it will default to the value of OMNITRACE_COLLAPSE_PROCESSES  |
| OMNITRACE_PERFETTO_SHMEM_SIZE_HINT_KB     | Hint for shared-memory buffer size in perfetto (in KB)                                                        |
| OMNITRACE_PRECISION                       | Set the global output precision for components                                                                |
| OMNITRACE_SAMPLING_CPUTIME                | Enable sampling frequency via a timer that measures both CPU time used by the current process, and CPU tim... |
| OMNITRACE_SAMPLING_DELAY                  | Time (in seconds) to wait before the first sampling signal is delivered, increasing this value can fix dea... |
| OMNITRACE_SAMPLING_KEEP_INTERNAL          | Configure whether the statistical samples should include call-stack entries from internal routines in omni... |
| OMNITRACE_SAMPLING_REALTIME_OFFSET        | Modify this value only if the target process is also using SIGRTMIN. E.g. the signal used is SIGRTMIN + <T... |
| OMNITRACE_STRICT_CONFIG                   | Throw errors for unknown setting names in configuration files instead of emitting a warning                   |
| OMNITRACE_SUPPRESS_CONFIG                 | Disable processing of setting configuration files                                                             |
| OMNITRACE_SUPPRESS_PARSING                | Disable parsing environment                                                                                   |
| OMNITRACE_TEXT_OUTPUT                     | Write text output files                                                                                       |
| OMNITRACE_TIMELINE_PROFILE                | Set the label hierarchy mode to default to timeline                                                           |
| OMNITRACE_TIMELINE_SAMPLING               | Create unique entries for every sample when statistical sampling is enabled                                   |
| OMNITRACE_TIMEMORY_COMPONENTS             | List of components to collect via timemory (see `omnitrace-avail -C`)                                         |
| OMNITRACE_TIME_FORMAT                     | Customize the folder generation when TIME_OUTPUT is enabled (see also: strftime)                              |
| OMNITRACE_TIME_OUTPUT                     | Output data to subfolder w/ a timestamp (see also: TIME_FORMAT)                                               |
| OMNITRACE_TIMING_PRECISION                | Set the precision for components with 'is_timing_category' type-trait                                         |
| OMNITRACE_TIMING_SCIENTIFIC               | Set the numerical reporting format for components with 'is_timing_category' type-trait                        |
| OMNITRACE_TIMING_UNITS                    | Set the units for components with 'uses_timing_units' type-trait                                              |
| OMNITRACE_TIMING_WIDTH                    | Set the output width for components with 'is_timing_category' type-trait                                      |
| OMNITRACE_TREE_OUTPUT                     | Write hierarchical json output files                                                                          |
| OMNITRACE_USE_CODE_COVERAGE               | Enable support for code coverage                                                                              |
| OMNITRACE_WIDTH                           | Set the global output width for components
