### ISSUE TITLE
Feature: capture stack traces of API tracing

### ISSUE THREAD

**Issue by Maetveis** [AMDResearch/omnitrace#198]
For API tracing (like HIP and MPI traces) it would be nice to see the call stack.
My use case is tracking down where certain slow or undesirable calls come from i.e. `hipMalloc`. Commonly these functions are not big enough to get selected by the default heuristics, and also may come from external libraries which might not be instrumented.

**Comment by jrmadsen** [comment]
There's a large list of options, see: `omnitrace-avail -c sampling --advanced`

**Comment by Maetveis** [comment]
> Are you aware that you can set OMNITRACE_USE_SAMPLING=ON and get call stack samples intermixed with instrumentation?

Yes I'm aware, but sampling isn't exact so it would be better to have it as part of tracing. Would it be possible to unwind the stack in the roctracer callback?

**Comment by jrmadsen** [comment]
> Would it be possible to unwind the stack in the roctracer callback?

Yes, it's possible to get this info in the callback. The primary issue is where to place it in the output since I don't want to stick an entire unwind call-stack into an existing instrumentation call-stack. It would be possible to add an option that, when enabled, adds the backtrace to the perfetto debug annotations.

**Comment by jrmadsen** [comment]
This won't be a quick addition though (i.e. something I can do in a day). I'll have to take care to make this restrictive to only happen in certain places bc broadly doing this when the option is enabled would cause very large overhead -- normally when sampling, I just save the instruction pointers for the call-stack and map them to function names, etc. during finalization. But in order to do this, I'll need to do that while the instrumentation is running and even though a lot of the IP -> info lookup overhead will be mitigated by using a cache, it will still be a lot of dynamic string generation

**Comment by Maetveis** [comment]
> The primary issue is where to place it in the output since I don't want to stick an entire unwind call-stack into an existing instrumentation call-stack.

Yeah that's tricky and merging it probably would be hard because the call stack is only reconstructed by perfetto.

> This won't be a quick addition though (i.e. something I can do in a day). I'll have to take care to make this restrictive to only happen in certain places bc broadly doing this when the option is enabled would cause very large overhead 

If this is hard to do and it won't have the best experience i.e. call graphs just in a text form instead of the timeline, then it might not be worth it to implement in the end. There should always be the option to rewrite the API traced libraries themselves (i.e. amdhip64.so or libopenmpi.so) to get the call stacks.
Feel free to close the issue if you want.

**Comment by jrmadsen** [comment]
> There should always be the option to rewrite the API traced libraries themselves (i.e. amdhip64.so or libopenmpi.so) to get the call stacks. Feel free to close the issue if you want.

There is an option for [binary rewriting a library](https://amdresearch.github.io/omnitrace/instrumenting.html#binary-rewriting-a-library). However, certain libraries are kind of hard coded against instrumenting because they demonstrated a tendency to cause self-instrumentation. But I don't think either of those libraries are on the list.

Another alternative is to enable realtime sampling, either in lieu of or alongside cputime sampling. If you increase the frequency enough, you should see plenty of samples taken during those calls. Realtime sampling has a tendency to wake sleeping threads though so you might want to specify which thread IDs you want. There's lots of info in `omnitrace-avail -c sampling --advanced -d` or just generate a verbose config and modify accordingly: `omnitrace-avail -G sampling.cfg -c sampling --advanced --all`

**Comment by jrmadsen** [comment]
Although note that if you are using ROCm < 5.3, you need to set `HSA_ENABLE_INTERRUPT=0` in the env. There's a bug in older versions that will cause an ioctl call to never return if a sample is taken while waiting for a signal the kernel completed.

**Comment by jrmadsen** [comment]
Solved in #323
