### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by FabioLuporini** [AMDResearch/omnitrace#217]
Hi, we have a Dockerfile through which we install ROCm, ROCm-aware MPI and a bunch of other tools. We now want to add Omnitrace. There's a variety of install scripts, each install script related to a different OS and ROCm version. 

Currently we are hardcoding it:

https://github.com/devitocodes/devito/pull/2032/files#diff-a3137c0b257134498ab077869720fd864d4948c9d26f2e475746f16d821620b2R49

So here are my questions:

* Aside from hacking with bash to e.g. map ROCm 5.1.3 to "50100", is there a better way to get Omnitrace for a given ROCm version? 

* How are these naming conventions likely to change in the future? 

* And finally, any chance Omnitrace will ultimately make it into the official AMD Dockerfiles?

Thanks!

**Comment by jrmadsen** [comment]
> - Aside from hacking with bash to e.g. map ROCm 5.1.3 to "50100", is there a better way to get Omnitrace for a given ROCm version?

Basically, those numbers come from `/opt/rocm/.info/<file>` where file is one of the names you see [here](https://github.com/AMDResearch/omnitrace/blob/2449e7cd462672e3ff9f040c710dcac236af28be/cmake/Modules/FindROCmVersion.cmake#L222), e.g., `/opt/rocm/.info/version`. Which usually provides something like: `5.1.0-36`. From bash, I'd use: `cat /opt/rocm/.info/<file> | sed -r 's/[\.-]/ /g' | awk '{print 10000*$1+100*$2}'` (ignoring the patch number since the releases are always built against the 0th patch). The OS name and version can be extracted from `/etc/os-release`. Anything after rocm and the rocm version is essentially features/third-party-library-support, e.g. OMPT-PAPI-Python3 basically indicates it includes OpenMP-Tools, PAPI, and Python3 support. If I were to build releases with full MPI support (and thus requiring linking to MPI), it would follow a similar pattern as the rocm + version since versioning and distro is more important there. 

> - How are these naming conventions likely to change in the future?

The naming convention might change if/when more third-party libraries are incorporated but it's pretty stable at this point and building the release variants are fully automated so even in that scenario, I may just end up with more variants instead of changing them. Although I have considered dropping `-OMPT-PAPI` from the names since those have no runtime link dependencies. 

> - And finally, any chance Omnitrace will ultimately make it into the official AMD Dockerfiles?

Well, it's still classified as a research project and not officially part of the ROCm software stack. Right now, we are basically free to create releases whenever appropriate and trying to bundle it in the dockerfiles will likely result in us losing that freedom.
