### ISSUE TITLE
omnitrace needs dyninst-12.0.0 or higher

### ISSUE THREAD

**Issue by donners-atos** [AMDResearch/omnitrace#236]
The documentation mentions that dyninst-10 is the minimal requirement, but omnitrace cannot be compiled with a version below 12.0.0. Version 11.0.1 provides the isExecutable function and only from version 12 the BPatch objects can be printed using iostreams. An update of the documentation and possibly a check by CMake would be helpful.

**Comment by jrmadsen** [comment]
> The documentation mentions that dyninst-10 is the minimal requirement

This is a typo. It should be 11.0.1.

> but omnitrace cannot be compiled with a version below 12.0.0. 

How were you building omnitrace? What were the errors? Because omnitrace has Dyninst submodule that is _basically_ v11.0.1. Most of the changes were CMake related and largely had to do with use as a subproject and improvements to building the third-party dependencies as part of the build of Dyninst. There have been some bug fixes that I eventually had to do (and haven't contributed upstream to Dyninst because I am still waiting on the acceptance of the CMake changes) but any differences there would only be present during runtime.

**Comment by jrmadsen** [comment]
Oh nevermind, I am guessing the build error was related to BPatch objects printed as iostreams. I don't remember adding that but nonetheless, I'll update the docs to state that.

**Comment by donners-atos** [comment]
thanks.
