### ISSUE TITLE
 Segfault printing available for libfabric on Crusher w/ v1.2.0

### ISSUE THREAD

**Issue by arghdos** [AMDResearch/omnitrace#91]
$ source sw/omnitrace-devel/share/omnitrace/setup-env.sh
$ module load craype-accel-amd-gfx90a
$ module load PrgEnv-cray
$ module load rocm
$ omnitrace --print-available pair -- /opt/cray/libfabric/1.15.0.0/lib64/libfabric.so.1
[omnitrace][exe] 
[omnitrace][exe] command :: '/opt/cray/libfabric/1.15.0.0/lib64/libfabric.so.1.17.0'...
[omnitrace][exe] 
[omnitrace][exe] DYNINST_API_RT: /autofs/nccs-svm1_home1/nicurtis/sw/omnitrace-devel/lib/omnitrace/libdyninstAPI_RT.so.11.0.1
omnitrace: /ccs/home/nicurtis/omnitrace/external/dyninst/common/src/addrtranslate-linux.C:289: Dyninst::LoadedLib* Dyninst::AddressTranslateSysV::getAOut(): Assertion `phdr_vaddr != (Address) -1' failed.
Aborted

**Comment by jrmadsen** [comment]
Interesting, definitely looks like an internal dyninst error as opposed to something omnitrace is doing wrong. I'll have to get on crusher and debug instrumenting libfabric

**Comment by jrmadsen** [comment]
This looks like it could be the same circular dependency noted in https://github.com/AMDResearch/omnitrace/issues/92#issuecomment-1188559221 since without the `-o` flag, `libomnitrace-dl.so` and `libomnitrace.so` are getting loaded at runtime. 

Either that or this command doesn't work when it is passed a library. Without the `-o` or `-p` flag, omnitrace assumes the target is an executable and tries to start running the executable, which obviously will fail if the target binary is a library. Since this failure appears to happen so early, this is quite likely the case although I would have expected a different error message.
